final Map<String, List<Map<String, String>>> routes = {
  'Bus #1': [
    {'stop': 'Chandni Chowk', 'time': '07:05 AM'},
    {'stop': 'Arshi Masjid', 'time': '07:08 AM'},
    {'stop': 'Khana e Farhang', 'time': '07:10 AM'},
    {'stop': 'Raees-ul-Ahrar', 'time': '07:15 AM'},
    {'stop': 'Sufi Baker', 'time': '07:18 AM'},
    {'stop': 'Suzuki Motors', 'time': '07:20 AM'},
    {'stop': 'Girls College Chowk', 'time': '07:21 AM'},
    {'stop': 'Siddiqui Chowk', 'time': '07:22 AM'},
    {'stop': 'Caltex Petrol pump', 'time': '07:23 AM'},
    {'stop': 'Gulzar Hotel', 'time': '07:24 AM'},
    {'stop': 'Pindora Chungi', 'time': '07:25 AM'},
    {'stop': 'School Road I-9/4', 'time': '07:30 AM'},
    {'stop': 'i-9-police-station', 'time': '07:35 AM'},
    {'stop': 'University', 'time': '07:40 AM'},
  ],
  'Bus #2': [
    {'stop': 'Gulistan Colony Lane', 'time': '07:00 AM'},
    {'stop': 'Gulistan Colony Lane 5', 'time': '07:02 AM'},
    {'stop': 'Gulistan Lane Colony 3', 'time': '07:05 AM'},
    {'stop': 'Askari 1', 'time': '07:07 AM'},
    {'stop': 'Askari 3', 'time': '07:08 AM'},
    {'stop': 'Rawal Chowk', 'time': '07:10 AM'},
    {'stop': 'Old Airport', 'time': '07:13 AM'},
    {'stop': 'Shah Khalid', 'time': '07:15 AM'},
    {'stop': 'Gulzar e Quaid', 'time': '07:20 AM'},
    {'stop': 'University', 'time': '07:40 AM'},
  ],
  'Bus #3': [
    {'stop': 'Media Town', 'time': '07:10 AM'},
    {'stop': 'National Bank', 'time': '07:15 AM'},
    {'stop': 'Tehzeeb Bakers', 'time': '07:20 AM'},
    {'stop': 'Bara Plaza PWD', 'time': '07:25 AM'},
    {'stop': 'Gourmet Bakers & Sweet PWD', 'time': '07:30 AM'},
    {'stop': 'PWD London Bakers', 'time': '07:35 AM'},
    {'stop': 'University', 'time': '07:45 AM'},
  ],
  'Bus #4': [
    {'stop': 'F-10 Sumbal Road', 'time': '07:05 AM'},
    {'stop': 'F-10/2 Ahmed Faraz Road', 'time': '07:08 AM'},
    {'stop': 'E-11 Quba Masjid', 'time': '07:10 AM'},
    {'stop': 'Darbar Chowk', 'time': '07:15 AM'},
    {'stop': 'F-11 Markaz', 'time': '07:18 AM'},
    {'stop': 'F-11 Hall Road', 'time': '07:20 AM'},
    {'stop': 'G-11/3 Ibn e sina Road', 'time': '07:21 AM'},
    {'stop': 'AK Brohi Road', 'time': '07:22 AM'},
    {'stop': 'G-10/2', 'time': '07:23 AM'},
    {'stop': 'G-10 Bela Road', 'time': '07:24 AM'},
    {'stop': 'KRL Hospital', 'time': '07:25 AM'},
    {'stop': 'University', 'time': '07:40 AM'},
  ],
  'Bus #5': [
    {'stop': 'Marir Hassan', 'time': '07:05 AM'},
    {'stop': 'Punjab House', 'time': '07:08 AM'},
    {'stop': 'Panj Sarki', 'time': '07:10 AM'},
    {'stop': 'Moti Mahal', 'time': '07:15 AM'},
    {'stop': 'Sir syed chowk', 'time': '07:18 AM'},
    {'stop': 'Scheme 2', 'time': '07:20 AM'},
    {'stop': 'Fauji Tower Petrol Pump', 'time': '07:21 AM'},
    {'stop': 'PAF Gate', 'time': '07:22 AM'},
    {'stop': 'Ali Nawaz Chowk', 'time': '07:23 AM'},
    {'stop': 'Qureshi Mor Rawal Road', 'time': '07:24 AM'},
    {'stop': 'Chandni Chowk', 'time': '07:25 AM'},
    {'stop': 'Al Janat Mall. Commercial Market', 'time': '07:27 AM'},
    {'stop': 'Tehzeeb Bakers', 'time': '07:28 AM'},
    {'stop': 'Filtration Plant', 'time': '07:29 AM'},
    {'stop': 'College Chowk', 'time': '07:30 AM'},
  ],
  'Bus #6': [
    {'stop': 'NUST', 'time': '07:05 AM'},
    {'stop': 'Sain Mirchu', 'time': '07:08 AM'},
    {'stop': 'Chungi No 26', 'time': '07:10 AM'},
    {'stop': 'PSO Pump Chungi No.26', 'time': '07:15 AM'},
    {'stop': 'Zoom Pump', 'time': '07:18 AM'},
    {'stop': 'Khyban e Kashmir G-15', 'time': '07:20 AM'},
    {'stop': 'G-13 Babrus Abbas Road', 'time': '07:21 AM'},
    {'stop': 'Srinagar Highway G-14', 'time': '07:22 AM'},
    {'stop': 'G-14 Filtration Plant', 'time': '07:23 AM'},
    {'stop': 'Sirinagar Highway N-5', 'time': '07:24 AM'},
  ],
  'Bus #7': [
    {'stop': 'Khana Pull Rawalpindi', 'time': '07:05 AM'},
    {'stop': 'Trali ada', 'time': '07:08 AM'},
    {'stop': 'Abdullah Masjid', 'time': '07:10 AM'},
    {'stop': 'Fazal e Rabbi Bakers', 'time': '07:15 AM'},
    {'stop': 'Jahaz Ground', 'time': '07:18 AM'},
    {'stop': 'Jinnah Camp', 'time': '07:20 AM'},
    {'stop': 'Jalebi Chowk', 'time': '07:21 AM'},
    {'stop': 'Chungi No.8', 'time': '07:22 AM'},
    {'stop': 'Caltex Petrol pump', 'time': '07:23 AM'},
    {'stop': 'Haji Chowk', 'time': '07:24 AM'},
    {'stop': 'Allied Bank Stop', 'time': '07:25 AM'},
    {'stop': 'Alfalah Bakers & Sweet', 'time': '07:26 AM'},
    {'stop': 'Sadiq abad Chowk', 'time': '07:27 AM'},
    {'stop': 'Rashid Colony', 'time': '07:28 AM'},
  ],
  'Bus #8': [
    {'stop': 'Marriage Hall', 'time': '07:05 AM'},
    {'stop': 'Abbasi Hotel', 'time': '07:08 AM'},
    {'stop': 'Jillani Stop', 'time': '07:10 AM'},
    {'stop': 'Shahdara stop', 'time': '07:15 AM'},
    {'stop': 'Malpur stop', 'time': '07:18 AM'},
    {'stop': 'Serena Chowk', 'time': '07:20 AM'},
    {'stop': 'Embassy Road Chowk', 'time': '07:21 AM'},
    {'stop': 'Aabpara Chowk', 'time': '07:22 AM'},
    {'stop': 'Fire Brigade', 'time': '07:23 AM'},
    {'stop': 'Zero Point', 'time': '07:24 AM'},
  ],
  'Bus #9': [
    {'stop': 'Caltax Road', 'time': '07:05 AM'},
    {'stop': 'Askari 14', 'time': '07:08 AM'},
    {'stop': 'Gulshan Abad', 'time': '07:10 AM'},
    {'stop': 'Cash & Carry', 'time': '07:15 AM'},
    {'stop': 'Gulshan Abad Gate 3', 'time': '07:18 AM'},
    {'stop': 'Gulshan Abad Markaz', 'time': '07:20 AM'},
    {'stop': 'Adyala Road Gulshan Abad Gate', 'time': '07:21 AM'},
    {'stop': 'Jarahi Stop', 'time': '07:22 AM'},
    {'stop': 'Munawar Colony', 'time': '07:23 AM'},
    {'stop': 'Dhama Mor', 'time': '07:24 AM'},
  ],
  'Bus #10': [
    {'stop': 'Sadar House Colony', 'time': '07:05 AM'},
    {'stop': 'PM Colony', 'time': '07:08 AM'},
    {'stop': 'Ayub Chowk', 'time': '07:10 AM'},
    {'stop': 'Super market', 'time': '07:15 AM'},
    {'stop': 'Melody', 'time': '07:18 AM'},
    {'stop': '1.2 Stop', 'time': '07:20 AM'},
    {'stop': 'Iqbal Hall', 'time': '07:21 AM'},
    {'stop': 'Khada Market', 'time': '07:22 AM'},
    {'stop': 'Sitara Market Tanki', 'time': '07:23 AM'},
    {'stop': 'Service road', 'time': '07:24 AM'},
  ],
  'Bus #11': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #12': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #13': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #14': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #15': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #16': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #17': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #18': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #19': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #20': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #21': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #22': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #23': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #24': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #25': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #26': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #27': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #28': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #29': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #30': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #31': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
  'Bus #32': [
    {'stop': 'Placeholder Stop', 'time': '07:00 AM'},
    {'stop': 'University', 'time': '07:30 AM'},
  ],
};
