// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCwIegbRpvmrfqsZigscpWj3ANiy_fVis',
    appId: '1:793999488248:web:89bea65a1639a6fc5e370d',
    messagingSenderId: '793999488248',
    projectId: 'fyp-feedback-flow-b588e',
    authDomain: 'fyp-feedback-flow-b588e.firebaseapp.com',
    storageBucket: 'fyp-feedback-flow-b588e.firebasestorage.app',
    measurementId: 'G-VGLZ6393DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSx4DP8z7sBpHjQnJPFoCR2ZT7qZOYj6k',
    appId: '1:793999488248:android:ef0dd755cc83ae7b5e370d',
    messagingSenderId: '793999488248',
    projectId: 'fyp-feedback-flow-b588e',
    storageBucket: 'fyp-feedback-flow-b588e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjeKsHacrsq1Sft3Cqlq9L4STRIqAak7g',
    appId: '1:793999488248:ios:4f4ac8f200a453bf5e370d',
    messagingSenderId: '793999488248',
    projectId: 'fyp-feedback-flow-b588e',
    storageBucket: 'fyp-feedback-flow-b588e.firebasestorage.app',
    iosBundleId: 'com.example.fypFeedbackFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjeKsHacrsq1Sft3Cqlq9L4STRIqAak7g',
    appId: '1:793999488248:ios:4f4ac8f200a453bf5e370d',
    messagingSenderId: '793999488248',
    projectId: 'fyp-feedback-flow-b588e',
    storageBucket: 'fyp-feedback-flow-b588e.firebasestorage.app',
    iosBundleId: 'com.example.fypFeedbackFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCwIegbRpvmrfqsZigscpWj3ANiy_fVis',
    appId: '1:793999488248:web:5d8afbffa3a6e83c5e370d',
    messagingSenderId: '793999488248',
    projectId: 'fyp-feedback-flow-b588e',
    authDomain: 'fyp-feedback-flow-b588e.firebaseapp.com',
    storageBucket: 'fyp-feedback-flow-b588e.firebasestorage.app',
    measurementId: 'G-W1XS6E9J8E',
  );
}
